################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../CDataToMessageOK.cpp \
../CHexToInt.cpp \
../CIOCom.cpp \
../CPEDPUSHBUTTON.cpp \
../CPacketCluster.cpp \
../CPhaseInfo.cpp \
../CPlanInfo.cpp \
../CREATEXML.cpp \
../CRTMSDecoder.cpp \
../CRTMSInformation.cpp \
../CReverseTime.cpp \
../CSTC.cpp \
../CSTORINI.cpp \
../CSegmentInfo.cpp \
../CTIMER.cpp \
../CTools.cpp \
../CTrafficAnalyzer.cpp \
../ConfigFile.cpp \
../DIGITALIO.cpp \
../DYNCTLJOB.cpp \
../IODEVICE.cpp \
../JOB.cpp \
../LCD240x128.cpp \
../PARSE.cpp \
../PARSENMEA.cpp \
../PARSERTMS.cpp \
../PARSESS.cpp \
../PARSETRAFFIC.cpp \
../PARSEV3.cpp \
../PDEVICE.cpp \
../PDEVICEKEYPAD.cpp \
../PDEVICEPEDPUSHBUTTON.cpp \
../PDEVICEREVMANUALPAD.cpp \
../PDEVICERTMS.cpp \
../PDEVICESS.cpp \
../PDEVICETRAFFICLIGHT.cpp \
../PROTOCOL.cpp \
../PTRAFFIC.cpp \
../PTRAFFIC77.cpp \
../PTRAFFIC87.cpp \
../PTRAFFIC87CMS.cpp \
../PTRAFFIC87COMM.cpp \
../PTRAFFIC87TC.cpp \
../PTRAFFIC87VD.cpp \
../PTRAFFIC92.cpp \
../PTRAFFIC92BRT.cpp \
../PTRAFFIC92CMS.cpp \
../PTRAFFIC92COMM.cpp \
../PTRAFFIC92COUNTDOWN.cpp \
../PTRAFFIC92OTHER.cpp \
../PTRAFFIC92TC.cpp \
../PTRAFFIC92VD.cpp \
../PTRAFFIC92WEB.cpp \
../PTRAFFICAMEGIDS.cpp \
../PTRAFFICCCJ.cpp \
../PTRAFFICNTCIP.cpp \
../PTRAFFICREVSYNC.cpp \
../READJOB.cpp \
../RS232.cpp \
../SCREEN.cpp \
../SCREENABOErr.cpp \
../SCREENActuateArwenLongGreenStatus.cpp \
../SCREENActuateStrategyMenu.cpp \
../SCREENCmdSet.cpp \
../SCREENCommStat.cpp \
../SCREENControlStrategyMenu.cpp \
../SCREENCtlNo.cpp \
../SCREENCtlSetup.cpp \
../SCREENDBSetup.cpp \
../SCREENDirMap.cpp \
../SCREENFWVerDT.cpp \
../SCREENHWCycle.cpp \
../SCREENHWReset.cpp \
../SCREENLast92TCPlanSegmentUpdate.cpp \
../SCREENLastDown.cpp \
../SCREENLcnEncode.cpp \
../SCREENLightBoardMap.cpp \
../SCREENLockdb.cpp \
../SCREENLogin.cpp \
../SCREENLoginErr.cpp \
../SCREENLogo.cpp \
../SCREENMBSelect.cpp \
../SCREENMain.cpp \
../SCREENModifyDT.cpp \
../SCREENModifyPWD.cpp \
../SCREENNetmaskSet.cpp \
../SCREENNetworkSet.cpp \
../SCREENNetworkSetConfirm.cpp \
../SCREENNone.cpp \
../SCREENOffline.cpp \
../SCREENOnline.cpp \
../SCREENOperMode.cpp \
../SCREENOperStat.cpp \
../SCREENPedSignalHWSet.cpp \
../SCREENPedSignalMenu.cpp \
../SCREENPedSwitchStatus.cpp \
../SCREENRedCountMap.cpp \
../SCREENSendCycle.cpp \
../SCREENSystemInfoMenu.cpp \
../SCREENTFDStatus.cpp \
../SCREENTotalRun.cpp \
../SCREENUart2.cpp \
../SCREENUpdateDB.cpp \
../SCREENV3Related.cpp \
../SCREENWarning.cpp \
../SMEM.cpp \
../STORAGE.cpp \
../ScreenActuateArwenFlashManyStatus.cpp \
../ScreenActuateArwenMenu.cpp \
../UDP.cpp \
../WRITEJOB.cpp \
../inifile.cpp \
../light.cpp \
../main.cpp \
../screenActuateArwenManyStatus.cpp \
../screenActuateArwenManyStatus2.cpp \
../screenActuateArwenStatus.cpp \
../screenActuateArwenVDInfo.cpp \
../screenActuateBUSEdit.cpp \
../screenActuateEdit.cpp \
../screenActuatePlaySwitch.cpp \
../screenCarCountdownProperty.cpp \
../screenCarLearn.cpp \
../screenChainMenu.cpp \
../screenChainStatus.cpp \
../screenChildChainSet.cpp \
../screenCommunication.cpp \
../screenCompensationset.cpp \
../screenCountdownProperty.cpp \
../screenCurrentCommPacket.cpp \
../screenCurrentLightStatus.cpp \
../screenDirLightBoardMappingMenu.cpp \
../screenFlashMode.cpp \
../screenLightEdit.cpp \
../screenLightPreview.cpp \
../screenMotherChainSet.cpp \
../screenPassModeSet.cpp \
../screenPedCountdownProperty.cpp \
../screenPedLearn.cpp \
../screenPhasePreview.cpp \
../screenPlan.cpp \
../screenPlanEdit0523.cpp \
../screenPlanEditF2.cpp \
../screenPlanPreview.cpp \
../screenPriority.cpp \
../screenPriorityExtendsec.cpp \
../screenPrioritymenu.cpp \
../screenRTMSInfo.cpp \
../screenRailwayChainSet.cpp \
../screenRedCountHWCheck.cpp \
../screenRedCountHWCheckCycleNum.cpp \
../screenRedCountHWCheckDevID.cpp \
../screenRedCountHWCheckNum88.cpp \
../screenRedCountHWCheckSel.cpp \
../screenRedCountHWVerMenu.cpp \
../screenRedCountMenu.cpp \
../screenRevSpecialDay.cpp \
../screenRevWeekDay.cpp \
../screenReverse.cpp \
../screenReverseMenu.cpp \
../screenRunTableList.cpp \
../screenSegmentVDPhaseMapTableEdit.cpp \
../screenSegtype.cpp \
../screenSegtypeEditF2.cpp \
../screenSegtypeMenu.cpp \
../screenSegtypePreview.cpp \
../screenSegtypeSel.cpp \
../screenSpecialDay.cpp \
../screenSpecialDayEditF2.cpp \
../screenSpecialDayView.cpp \
../screenStrategy.cpp \
../screenVDActPhaseEdit.cpp \
../screenVDPhaseMapTable.cpp \
../screenVDPhaseMapTableEdit.cpp \
../screenWeekDay.cpp \
../screenWeekDayEditF2.cpp 

OBJS += \
./CDataToMessageOK.o \
./CHexToInt.o \
./CIOCom.o \
./CPEDPUSHBUTTON.o \
./CPacketCluster.o \
./CPhaseInfo.o \
./CPlanInfo.o \
./CREATEXML.o \
./CRTMSDecoder.o \
./CRTMSInformation.o \
./CReverseTime.o \
./CSTC.o \
./CSTORINI.o \
./CSegmentInfo.o \
./CTIMER.o \
./CTools.o \
./CTrafficAnalyzer.o \
./ConfigFile.o \
./DIGITALIO.o \
./DYNCTLJOB.o \
./IODEVICE.o \
./JOB.o \
./LCD240x128.o \
./PARSE.o \
./PARSENMEA.o \
./PARSERTMS.o \
./PARSESS.o \
./PARSETRAFFIC.o \
./PARSEV3.o \
./PDEVICE.o \
./PDEVICEKEYPAD.o \
./PDEVICEPEDPUSHBUTTON.o \
./PDEVICEREVMANUALPAD.o \
./PDEVICERTMS.o \
./PDEVICESS.o \
./PDEVICETRAFFICLIGHT.o \
./PROTOCOL.o \
./PTRAFFIC.o \
./PTRAFFIC77.o \
./PTRAFFIC87.o \
./PTRAFFIC87CMS.o \
./PTRAFFIC87COMM.o \
./PTRAFFIC87TC.o \
./PTRAFFIC87VD.o \
./PTRAFFIC92.o \
./PTRAFFIC92BRT.o \
./PTRAFFIC92CMS.o \
./PTRAFFIC92COMM.o \
./PTRAFFIC92COUNTDOWN.o \
./PTRAFFIC92OTHER.o \
./PTRAFFIC92TC.o \
./PTRAFFIC92VD.o \
./PTRAFFIC92WEB.o \
./PTRAFFICAMEGIDS.o \
./PTRAFFICCCJ.o \
./PTRAFFICNTCIP.o \
./PTRAFFICREVSYNC.o \
./READJOB.o \
./RS232.o \
./SCREEN.o \
./SCREENABOErr.o \
./SCREENActuateArwenLongGreenStatus.o \
./SCREENActuateStrategyMenu.o \
./SCREENCmdSet.o \
./SCREENCommStat.o \
./SCREENControlStrategyMenu.o \
./SCREENCtlNo.o \
./SCREENCtlSetup.o \
./SCREENDBSetup.o \
./SCREENDirMap.o \
./SCREENFWVerDT.o \
./SCREENHWCycle.o \
./SCREENHWReset.o \
./SCREENLast92TCPlanSegmentUpdate.o \
./SCREENLastDown.o \
./SCREENLcnEncode.o \
./SCREENLightBoardMap.o \
./SCREENLockdb.o \
./SCREENLogin.o \
./SCREENLoginErr.o \
./SCREENLogo.o \
./SCREENMBSelect.o \
./SCREENMain.o \
./SCREENModifyDT.o \
./SCREENModifyPWD.o \
./SCREENNetmaskSet.o \
./SCREENNetworkSet.o \
./SCREENNetworkSetConfirm.o \
./SCREENNone.o \
./SCREENOffline.o \
./SCREENOnline.o \
./SCREENOperMode.o \
./SCREENOperStat.o \
./SCREENPedSignalHWSet.o \
./SCREENPedSignalMenu.o \
./SCREENPedSwitchStatus.o \
./SCREENRedCountMap.o \
./SCREENSendCycle.o \
./SCREENSystemInfoMenu.o \
./SCREENTFDStatus.o \
./SCREENTotalRun.o \
./SCREENUart2.o \
./SCREENUpdateDB.o \
./SCREENV3Related.o \
./SCREENWarning.o \
./SMEM.o \
./STORAGE.o \
./ScreenActuateArwenFlashManyStatus.o \
./ScreenActuateArwenMenu.o \
./UDP.o \
./WRITEJOB.o \
./inifile.o \
./light.o \
./main.o \
./screenActuateArwenManyStatus.o \
./screenActuateArwenManyStatus2.o \
./screenActuateArwenStatus.o \
./screenActuateArwenVDInfo.o \
./screenActuateBUSEdit.o \
./screenActuateEdit.o \
./screenActuatePlaySwitch.o \
./screenCarCountdownProperty.o \
./screenCarLearn.o \
./screenChainMenu.o \
./screenChainStatus.o \
./screenChildChainSet.o \
./screenCommunication.o \
./screenCompensationset.o \
./screenCountdownProperty.o \
./screenCurrentCommPacket.o \
./screenCurrentLightStatus.o \
./screenDirLightBoardMappingMenu.o \
./screenFlashMode.o \
./screenLightEdit.o \
./screenLightPreview.o \
./screenMotherChainSet.o \
./screenPassModeSet.o \
./screenPedCountdownProperty.o \
./screenPedLearn.o \
./screenPhasePreview.o \
./screenPlan.o \
./screenPlanEdit0523.o \
./screenPlanEditF2.o \
./screenPlanPreview.o \
./screenPriority.o \
./screenPriorityExtendsec.o \
./screenPrioritymenu.o \
./screenRTMSInfo.o \
./screenRailwayChainSet.o \
./screenRedCountHWCheck.o \
./screenRedCountHWCheckCycleNum.o \
./screenRedCountHWCheckDevID.o \
./screenRedCountHWCheckNum88.o \
./screenRedCountHWCheckSel.o \
./screenRedCountHWVerMenu.o \
./screenRedCountMenu.o \
./screenRevSpecialDay.o \
./screenRevWeekDay.o \
./screenReverse.o \
./screenReverseMenu.o \
./screenRunTableList.o \
./screenSegmentVDPhaseMapTableEdit.o \
./screenSegtype.o \
./screenSegtypeEditF2.o \
./screenSegtypeMenu.o \
./screenSegtypePreview.o \
./screenSegtypeSel.o \
./screenSpecialDay.o \
./screenSpecialDayEditF2.o \
./screenSpecialDayView.o \
./screenStrategy.o \
./screenVDActPhaseEdit.o \
./screenVDPhaseMapTable.o \
./screenVDPhaseMapTableEdit.o \
./screenWeekDay.o \
./screenWeekDayEditF2.o 

CPP_DEPS += \
./CDataToMessageOK.d \
./CHexToInt.d \
./CIOCom.d \
./CPEDPUSHBUTTON.d \
./CPacketCluster.d \
./CPhaseInfo.d \
./CPlanInfo.d \
./CREATEXML.d \
./CRTMSDecoder.d \
./CRTMSInformation.d \
./CReverseTime.d \
./CSTC.d \
./CSTORINI.d \
./CSegmentInfo.d \
./CTIMER.d \
./CTools.d \
./CTrafficAnalyzer.d \
./ConfigFile.d \
./DIGITALIO.d \
./DYNCTLJOB.d \
./IODEVICE.d \
./JOB.d \
./LCD240x128.d \
./PARSE.d \
./PARSENMEA.d \
./PARSERTMS.d \
./PARSESS.d \
./PARSETRAFFIC.d \
./PARSEV3.d \
./PDEVICE.d \
./PDEVICEKEYPAD.d \
./PDEVICEPEDPUSHBUTTON.d \
./PDEVICEREVMANUALPAD.d \
./PDEVICERTMS.d \
./PDEVICESS.d \
./PDEVICETRAFFICLIGHT.d \
./PROTOCOL.d \
./PTRAFFIC.d \
./PTRAFFIC77.d \
./PTRAFFIC87.d \
./PTRAFFIC87CMS.d \
./PTRAFFIC87COMM.d \
./PTRAFFIC87TC.d \
./PTRAFFIC87VD.d \
./PTRAFFIC92.d \
./PTRAFFIC92BRT.d \
./PTRAFFIC92CMS.d \
./PTRAFFIC92COMM.d \
./PTRAFFIC92COUNTDOWN.d \
./PTRAFFIC92OTHER.d \
./PTRAFFIC92TC.d \
./PTRAFFIC92VD.d \
./PTRAFFIC92WEB.d \
./PTRAFFICAMEGIDS.d \
./PTRAFFICCCJ.d \
./PTRAFFICNTCIP.d \
./PTRAFFICREVSYNC.d \
./READJOB.d \
./RS232.d \
./SCREEN.d \
./SCREENABOErr.d \
./SCREENActuateArwenLongGreenStatus.d \
./SCREENActuateStrategyMenu.d \
./SCREENCmdSet.d \
./SCREENCommStat.d \
./SCREENControlStrategyMenu.d \
./SCREENCtlNo.d \
./SCREENCtlSetup.d \
./SCREENDBSetup.d \
./SCREENDirMap.d \
./SCREENFWVerDT.d \
./SCREENHWCycle.d \
./SCREENHWReset.d \
./SCREENLast92TCPlanSegmentUpdate.d \
./SCREENLastDown.d \
./SCREENLcnEncode.d \
./SCREENLightBoardMap.d \
./SCREENLockdb.d \
./SCREENLogin.d \
./SCREENLoginErr.d \
./SCREENLogo.d \
./SCREENMBSelect.d \
./SCREENMain.d \
./SCREENModifyDT.d \
./SCREENModifyPWD.d \
./SCREENNetmaskSet.d \
./SCREENNetworkSet.d \
./SCREENNetworkSetConfirm.d \
./SCREENNone.d \
./SCREENOffline.d \
./SCREENOnline.d \
./SCREENOperMode.d \
./SCREENOperStat.d \
./SCREENPedSignalHWSet.d \
./SCREENPedSignalMenu.d \
./SCREENPedSwitchStatus.d \
./SCREENRedCountMap.d \
./SCREENSendCycle.d \
./SCREENSystemInfoMenu.d \
./SCREENTFDStatus.d \
./SCREENTotalRun.d \
./SCREENUart2.d \
./SCREENUpdateDB.d \
./SCREENV3Related.d \
./SCREENWarning.d \
./SMEM.d \
./STORAGE.d \
./ScreenActuateArwenFlashManyStatus.d \
./ScreenActuateArwenMenu.d \
./UDP.d \
./WRITEJOB.d \
./inifile.d \
./light.d \
./main.d \
./screenActuateArwenManyStatus.d \
./screenActuateArwenManyStatus2.d \
./screenActuateArwenStatus.d \
./screenActuateArwenVDInfo.d \
./screenActuateBUSEdit.d \
./screenActuateEdit.d \
./screenActuatePlaySwitch.d \
./screenCarCountdownProperty.d \
./screenCarLearn.d \
./screenChainMenu.d \
./screenChainStatus.d \
./screenChildChainSet.d \
./screenCommunication.d \
./screenCompensationset.d \
./screenCountdownProperty.d \
./screenCurrentCommPacket.d \
./screenCurrentLightStatus.d \
./screenDirLightBoardMappingMenu.d \
./screenFlashMode.d \
./screenLightEdit.d \
./screenLightPreview.d \
./screenMotherChainSet.d \
./screenPassModeSet.d \
./screenPedCountdownProperty.d \
./screenPedLearn.d \
./screenPhasePreview.d \
./screenPlan.d \
./screenPlanEdit0523.d \
./screenPlanEditF2.d \
./screenPlanPreview.d \
./screenPriority.d \
./screenPriorityExtendsec.d \
./screenPrioritymenu.d \
./screenRTMSInfo.d \
./screenRailwayChainSet.d \
./screenRedCountHWCheck.d \
./screenRedCountHWCheckCycleNum.d \
./screenRedCountHWCheckDevID.d \
./screenRedCountHWCheckNum88.d \
./screenRedCountHWCheckSel.d \
./screenRedCountHWVerMenu.d \
./screenRedCountMenu.d \
./screenRevSpecialDay.d \
./screenRevWeekDay.d \
./screenReverse.d \
./screenReverseMenu.d \
./screenRunTableList.d \
./screenSegmentVDPhaseMapTableEdit.d \
./screenSegtype.d \
./screenSegtypeEditF2.d \
./screenSegtypeMenu.d \
./screenSegtypePreview.d \
./screenSegtypeSel.d \
./screenSpecialDay.d \
./screenSpecialDayEditF2.d \
./screenSpecialDayView.d \
./screenStrategy.d \
./screenVDActPhaseEdit.d \
./screenVDPhaseMapTable.d \
./screenVDPhaseMapTableEdit.d \
./screenWeekDay.d \
./screenWeekDayEditF2.d 


# Each subdirectory must supply rules for building sources it contributes
%.o: ../%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	/opt/crosstool/bin/g++-3.4 -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


